### ISSUE TITLE
Update Docker-related files

### ISSUE THREAD

**Issue by matheusd** [decred/dcrlnd#12]
Ideally used the original decred backed ones.

Original items from https://github.com/davecgh/dcrlnd/issues/1

- [ ] Rename docker/lnd to docker/dcrlnd and update
- [ ] Either rename docker/btcd to docker/dcrd or use existing dcrd docker repository
- [ ] Update docker/docker-compose.yml for dcrd, dcrctl, dcrlnd, dcrlncli, etc
- [ ] Update docker/README.md for Decred

**Comment by jholdstock** [comment]
Most of the docker changes are implemented here: https://github.com/decred/dcrlnd/compare/master...jholdstock:docker?expand=1

However this work cannot be completed right now as it is not possible to generate an address using dcrlnd until the chain is synced. The chain cannot be synced because the miner needs an address which is generated by dcrlnd (chicken and egg).

dcrwallet solves this problem by automatically outputting a address when it is started in simnet mode.

Related converstaion here: https://matrix.to/#/!doNReXWScHXhmjfGTa:decred.org/$155835555119306JGkYN:decred.org?via=decred.org&via=matrix.org&via=zettaport.com

Related issue: https://github.com/decred/dcrlnd/issues/9

**Comment by matheusd** [comment]
This setup definitely doesn't work as easily for us as it does for bitcoin due to voting requirements past SVH in simnet. You can't (e.g.) try to force close a channel and see a time-locked sweep tx due to it requiring more than 144 blocks to be redeemable.

Ideally we could setup a Minimum Voting Wallet to run along the dcrd node or just run an rpctest harness (with an associated MVW) which takes care of funding Alice and Bob.

**Comment by matheusd** [comment]
Did #66 completely fix this?

**Comment by fguisso** [comment]
following the checklist, yes
#56 and #66

**Comment by matheusd** [comment]
Thanks!
